# Generated by Django 5.1.2 on 2024-11-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_arranger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_period",
        ),
        migrations.AddField(
            model_name="classperiod",
            name="students",
            field=models.ManyToManyField(
                related_name="class_periods", to="seat_arranger.student"
            ),
        ),
    ]
